"""empty message

Revision ID: 53019a917fc6
Revises: ce39b10dfc7e
Create Date: 2022-08-03 09:23:30.530309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53019a917fc6'
down_revision = 'ce39b10dfc7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'create_time')
    # ### end Alembic commands ###
